### ISSUE TITLE
Does it support recurring?

### ISSUE THREAD

**Issue by florimm** [icenorge/PayEx.Client#5]
Does it support recurring?

**Comment by johnkors** [comment]
No, but looks easy to add, if I've understood [the docs correctly](https://developer.payex.com/xwiki/wiki/external/view/ecommerce/eCommerce%20Platform/Implementing%20Card%20Payments/Recurring%20card%20purchases/#HFirstPOSTrequest).

I think we just need to add three new properties. 

### To the [PaymentRequest](https://github.com/icenorge/PayEx.Client/blob/master/src/PayEx.Client/Models/Vipps/PaymentAPI/Request/PaymentRequest.cs) 

◀️ `"generatePaymentToken": "true|false"                    <-- Optional (default value is false)`
◀️ `"paymentToken": "5adc265f-f87f-4313-577e-08d3dca1a26c",`


and then 

### on the [PaymentResponse](https://github.com/icenorge/PayEx.Client/blob/master/src/PayEx.Client/Models/Vipps/PaymentAPI/Response/PaymentResponse.cs) 
..we need to add the token to be used on recurring payments

◀️ `"paymentToken": "5adc265f-f87f-4313-577e-08d3dca1a26c",     <-- Optional for operation=Purchase (only present if generatePaymentToken=true was specified)`

**Comment by johnkors** [comment]
Had a go at it, and recurring payments are now supported as of v2.1.0 and above.

* https://www.nuget.org/packages/PayEx.Client/2.1.0
* Sample integration can be found [here](https://github.com/icenorge/PayEx.Client/blob/master/src/Samples/Sample.AspNetCore/Controllers/DefaultController.cs) for the the different scenarios.
