### ISSUE TITLE
Cannot consume scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[PayEx.Client.PayExOptions]' from singleton

### ISSUE THREAD

**Issue by florimm** [icenorge/PayEx.Client#7]
Trying to use asp net core sample but I get this error:

```
An unhandled exception occurred while processing the request.
InvalidOperationException: Cannot consume scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[PayEx.Client.PayExOptions]' from singleton 'Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Http.HttpClientFactoryOptions]'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.VisitScoped(ScopedCallSite scopedCallSite, CallSiteValidatorState state)
```

**Comment by johnkors** [comment]
Cannot reproduce this. Are you on `master`?

**Comment by florimm** [comment]
Yes it was in master.

**Comment by johnkors** [comment]
Ok, strange. I cannot repro this. Try a fresh clone or git pull if you're out of date.

**Comment by nilssonm** [comment]
I'm still getting this with your latest release 4.0.0 from Nuget.

Now also tested with code cloned from the repo, which resulted with the same result.

**Comment by johnkors** [comment]
If you compare with the sample project, what is the diff? https://github.com/icenorge/PayEx.Client/blob/master/src/Samples/Sample.AspNetCore/Startup.cs

**Comment by nilssonm** [comment]
I have no difference in the service-registrations but still it gives me the error.
